sample/config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :contacts
  get'/kobatters/home' ,to:'kobatters#home'
  resources :kobatters do
    collection do
      post :confirm
    end
  end
end

sample/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample/app/models/kobatter.rb
class Kobatter < ApplicationRecord
  validates :content, presence: true
  validates :content, length:{maximum: 140}
end

sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample/app/controllers/kobatters_controller.rb
class KobattersController < ApplicationController
  before_action :set_kobatter, only: [:show, :edit, :update, :destroy]
  def home
  end
  def index
    @kobatters = Kobatter.all.order(id: "DESC")
    @count = Kobatter.all.count
  end
  def new
    @kobatter = Kobatter.new
  end
  def create
    @kobatter = Kobatter.new(kobatter_params)
    if params[:back]
      render :new
    else
      if @kobatter.save
        redirect_to kobatters_path, notice:"つぶやきを作成しました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @kobatter.update(kobatter_params)
      redirect_to kobatters_path, notice:"つぶやきを編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @kobatter.destroy
    redirect_to kobatters_path, notice:"ブログを削除しました！"
  end
  def confirm
    @kobatter = Kobatter.new(kobatter_params)
    render :new if @kobatter.invalid?
  end
  private
  def kobatter_params
    params.require(:kobatter).permit(:content)
  end
  def set_kobatter
    @kobatter = Kobatter.find(params[:id])
  end
end

sample/app/helpers/application_helper.rb
module ApplicationHelper
end

sample/app/helpers/kobatters_helper.rb
module KobattersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_kobatters_path
    elsif action_name == 'edit'
      kobatter_path
    end
  end
end

sample/app/views/kobatters/_form.html.erb
  <div class="wrapper clearfix">
    <aside class="side_menu">
      <p class="banner">
        <img src="/assets/party_animal.png">
      </p>
      <script>
      $(function() {
        $('.banner img').fadeIn(2000)
      });
      </script>
      <nav>
        <ul>
          <li>
            <img src="/assets/panda1.png" class="animal_image">
            <%= link_to 'トップページ', kobatters_home_path %>
          </li>
          <li>
            <img src="/assets/lion.png" class="animal_image">
            <%= link_to 'つぶやき一覧', kobatters_path %>
          </li>
          <li>
            <img src="/assets/zebra.png" class="animal_image">
            <%= link_to 'つぶやく', new_kobatter_path %>
          </li>
        </ul>
      </nav>
    </aside>
    <div class="new_form">
    <%= form_with(model: @kobatter, local:true , url:choose_new_or_edit) do |form| %>
      <% if @kobatter.errors.any? %>
        <div id="error_explanation">
          <h2><%= @kobatter.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @kobatter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="blog_title">
        <div><h1>内容を入力して「つぶやく」をクリック！</h1></div>
        <div class="blog_textfield"><%= form.text_area :content,size:"50x10", class:"content_border" %></div>
        <div><%= form.submit "つぶやく" %></div>
      </div>
    <% end %>
    </div>
  </div>

sample/app/views/kobatters/confirm.html.erb
<div class="wrapper clearfix">
  <aside class="side_menu">
    <p class="banner">
      <img src="/assets/tree_animals.png">
    </p>
    <script>
    $(function() {
      $('.banner img').fadeIn(2000)
    });
    </script>

    <nav>
      <ul>
        <li>
          <img src="/assets/panda1.png" class="animal_image">
          <%= link_to 'トップページ', kobatters_home_path %>
        </li>
        <li>
          <img src="/assets/lion.png" class="animal_image">
          <%= link_to 'つぶやき一覧', kobatters_path %>
        </li>
        <li>
          <img src="/assets/zebra.png" class="animal_image">
          <%= link_to 'つぶやく', new_kobatter_path %>
        </li>
      </ul>
    </nav>
  </aside>
  <article class="content">
    <div class="article_main">
      <h1>以下の内容でつぶやきますか？</h1>
        <div class="article_details">
        <%= form_with(model: @kobatter, local: true) do |form| %>
          <%= form.hidden_field :content %>
          <p><%= @kobatter.content %></p>
          <%= form.submit  "登録する" %>
          <%= form.submit "戻る", name: 'back' %>
        <% end %>
        </div>
    </div>
  </article>
</div>

sample/app/views/kobatters/edit.html.erb
<%= render 'form' %>

sample/app/views/kobatters/home.html.erb
  <ul class="panda_list">
    <li><img src="/assets/panda1.png" class="home_panda"></li>
    <li><img src="/assets/monkey.png" class="home_panda"></li>
    <li><img src="/assets/lion.png" class="home_panda"></li>
    <li><img src="/assets/blue_bird.png" class="home_panda"></li>
  </ul>
  <script>
    $(function(){
        $('.panda_list li, .home_text h1').each(function(i){
            $(this).delay(i * 500).css({visibility:'visible',opacity:'0'}).animate({opacity:'1'},3000);
        });
    });
  </script>

    <div class="home_text">
      <h1 id="home_text1">つぶやき動物園</h1>
      <h1><%= link_to 'つぶやき一覧へ', kobatters_path %></h1>
    </div>

sample/app/views/kobatters/index.html.erb
<div class="wrapper clearfix">
  <aside class="side_menu">
    <p class="banner">
      <img src="/assets/onsen_animals.png">
      <h2 class="panda_comment">動物園の出来事を毎日つぶやくよ！</h2>
      <h2 class="panda_comment">つぶやいた数：<%= @count %></h2>
    </p>
    <script>
    $(function() {
      $('.banner img').fadeIn(2000)
    });
    </script>
    <nav>
      <ul>
        <li>
          <img src="/assets/panda1.png" class="animal_image">
          <%= link_to 'トップページ', kobatters_home_path %>
        </li>
        <li>
          <img src="/assets/lion.png" class="animal_image">
          <%= link_to 'つぶやき一覧', kobatters_path %>
        </li>
        <li>
          <img src="/assets/zebra.png" class="animal_image">
          <%= link_to 'つぶやく', new_kobatter_path %>
        </li>
      </ul>
    </nav>
  </aside>
  <article class="content">
    <div class="article_main">
      <h1>つぶやき一覧</h1>
      <p><%= notice %></p>
      <% @kobatters.each do |kobatter| %>
        <div class="article_content">
          <div class="article_sentence"><%= kobatter.content %></div>
          <span><%= link_to '詳細を確認する', kobatter_path(kobatter.id) %></span>
          <span><%= link_to "ブログを編集する", edit_kobatter_path(kobatter.id) %></span>
          <span><%= link_to 'ブログを削除する', kobatter_path(kobatter.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></span>
          <span><%= kobatter.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span>
        </div>
      <% end %>
    </div>
  </article>
</div>

sample/app/views/kobatters/new.html.erb
<%= render 'form' %>

sample/app/views/kobatters/show.html.erb
<div class="wrapper clearfix">
  <aside class="side_menu">
    <p class="banner">
      <img src="/assets/car_animals.png">
    </p>
    <script>
    $(function() {
      $('.banner img').fadeIn(2000)
    });
    </script>
    <nav>
      <ul>
        <li>
          <img src="/assets/panda1.png" class="animal_image">
          <%= link_to 'トップページ', kobatters_home_path %>
        </li>
        <li>
          <img src="/assets/lion.png" class="animal_image">
          <%= link_to 'つぶやき一覧', kobatters_path %>
        </li>
        <li>
          <img src="/assets/zebra.png" class="animal_image">
          <%= link_to 'つぶやく', new_kobatter_path %>
        </li>
      </ul>
    </nav>
  </aside>
  <article class="content">
    <div class="article_main">
      <h1>ブログ詳細画面</h1>
      <div class="article_details">
        <p><%= @kobatter.content %></p>
        <span><%= link_to "ブログを編集する", edit_kobatter_path(@kobatter.id) %></span>
        <span><%= link_to 'ブログを削除する', kobatter_path(@kobatter.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></span>
      </div>
    </div>
  </article>
</div>

sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="header clearfix">
        <span class="logo_image"><%= link_to image_tag('logo.png'), kobatters_home_path %></span>
        <nav>
          <ul class="top_menu clearfix">
            <li><%= link_to 'トップページ', kobatters_home_path %></li>
            <li><%= link_to 'つぶやき一覧', kobatters_path %></li>
            <li><%= link_to 'つぶやく', new_kobatter_path %></li>
          </ul>
        </nav>
      </header>

      <%= yield %>

      <footer class="footer">
        <p>Copyright © 2020 TSUBUYAKI ZOO All RIGHTS RESERVED.</p>
      </footer>
    </div>
  </body>
</html>